spring:
  application:
    name: homework-spring-data-jpa

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:151003}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Consider 'validate' or 'none' for production
    show-sql: true       # Disable in production, enable only in dev
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true

logging:
  level:
    org.springframework.security: INFO

server:
  port: 8082